### PR TITLE
froglet in-progress

### PR DESCRIPTION
**Pull request by bennn**
- [X] context-sensitive join checks: `Tim.father` is ok, `Tim.father.grad` is ok, `Tim.Tim` is not ok, `father.grad` is not ok

### CODE REVIEW

**Comment by tnelson** [comment]
@bennn Can we close this PR?

**Comment by bennn** [comment]
unless someone else picked up froglet, we should merge this!

as-is, it's better than current froglet

of course i'd like to first get the tests passing

**Comment by bennn** [comment]
fixed merge conflicts, commented out lots of failing froglet tests ... let's see if CI passes

**Comment by bennn** [comment]
Phew CI passes, let's merge.

Next up: uncomment all those froglet tests in `error/main.rkt`!

**Pull request merged**
