### PR TITLE
add flag to hide preds

### PR DESCRIPTION
**Pull request by bennn**
Example:

```
#lang forge

sig Node {edges: set Node}

pred wheat hiddenPred {
    edges = ~edges
}

check { true } for { hiddenPred }
// without "wheat" = uncaught exception: "Invalid bind: (&& (&& (= (Relation edges) (~ (Relation edges)))))"
// with "wheat" = uncaught exception: "Invalid bind: #<wheat>"
```

### CODE REVIEW

**Comment by bennn** [comment]
Syntax suggestions welcome!

**Comment by bennn** [comment]
Ping @sidprasad . All wheats should use this, so students can't print them.

**Comment by tnelson** [comment]
Does this break `deparse`?

**Comment by bennn** [comment]
Yes it did. Added a `deparse` case.

Any ideas how to test deparse? I ran some local checks. Not sure how to create good input for `deparse`.

**Comment by bennn** [comment]
Update: planning to merge in a few days & start using for `forge2`

**Comment by bennn** [comment]
Merged so `forge2` can start hiding wheats. Sorry Tim if you get a merge conflict with pardinus!

**Pull request merged**
